import streamlit as st
import requests
import os

# Ensure backend URL is accessible
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000/api/v1")

st.set_page_config(page_title="SafeX Admin Dashboard", layout="wide")

st.title("SafeX Support Admin Dashboard")

# Simple Auth (Prototype)
def check_password():
    def password_entered():
        if st.session_state["password"] == "admin123": # Change for prod
            st.session_state["password_correct"] = True
            del st.session_state["password"]
        else:
            st.session_state["password_correct"] = False

    if "password_correct" not in st.session_state:
        st.text_input("Password", type="password", on_change=password_entered, key="password")
        return False
    elif not st.session_state["password_correct"]:
        st.text_input("Password", type="password", on_change=password_entered, key="password")
        st.error("😕 Password incorrect")
        return False
    else:
        return True

if check_password():
    tab1, tab2, tab3 = st.tabs(["Escalation Queue", "Pending FAQs", "Audit Logs"])

    with tab1:
        st.header("Escalation Queue")
        st.write("Here you can see user queries that triggered an escalation to human experts.")
        # We would make an API call to the backend to fetch escalations
        # e.g., requests.get(f"{BACKEND_URL}/admin/escalations")

    with tab2:
        st.header("Pending FAQs for Approval")
        st.write("The following FAQs were automatically generated by the clustering job based on recent user queries.")
        # We would make an API call to fetch pending FAQs
        
        col1, col2, col3 = st.columns([3, 3, 1])
        with col1:
            st.subheader("Question")
        with col2:
            st.subheader("Suggested Answer")
        with col3:
            st.subheader("Action")
            
        # Example row
        with col1:
            st.write("How do I reset my API key?")
        with col2:
            st.write("You can reset it in the dashboard under Settings -> API Keys.")
        with col3:
            st.button("Approve", key="approve_1")
            st.button("Reject", key="reject_1")

    with tab3:
        st.header("Audit Logs")
        st.write("View system audit logs, PII redactions, and guardrail blocks.")
